# Generated by Django 3.0.7 on 2021-01-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_client_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='client_db',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='note_db',
        ),
    ]
