# Generated by Django 3.0.7 on 2021-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210126_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_db',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
