# Generated by Django 3.0.7 on 2021-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_client_db_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note_db',
        ),
        migrations.AddField(
            model_name='client_db',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
