# Generated by Django 3.0.7 on 2021-01-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210127_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_db',
            name='client_id',
            field=models.TextField(blank=True),
        ),
    ]
