# Generated by Django 3.0.7 on 2021-01-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_client_db_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_db',
            old_name='address',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='ip',
            new_name='client_ip',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='note',
            new_name='client_note',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='phone',
            new_name='client_phone',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='url',
            new_name='client_url',
        ),
        migrations.RenameField(
            model_name='client_db',
            old_name='website',
            new_name='client_website',
        ),
    ]
