# Generated by Django 3.0.7 on 2021-01-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20210128_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_db',
            name='client_url',
        ),
    ]
