# Generated by Django 3.0.7 on 2021-01-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_client_db_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_db',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.client_db'),
        ),
        migrations.AddField(
            model_name='project_db',
            name='project_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
