# Generated by Django 3.0.7 on 2021-01-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210128_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='client',
            field=models.TextField(blank=True, null=True),
        ),
    ]
