# Generated by Django 3.0.7 on 2021-01-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210129_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='client',
            field=models.TextField(blank=True, null=True),
        ),
    ]
