# Generated by Django 3.0.7 on 2021-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20210131_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='client',
            field=models.TextField(blank=True, null=True),
        ),
    ]
