# Generated by Django 3.0.7 on 2021-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210131_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='project_disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_start',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_db',
            name='project_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
