# Generated by Django 3.0.7 on 2021-02-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210203_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_db',
            name='client_id',
            field=models.UUIDField(null=True),
        ),
    ]
