# Generated by Django 3.0.7 on 2021-03-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0017_auto_20201006_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvas_scan_db',
            name='high_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
