# Generated by Django 3.0.7 on 2021-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0019_auto_20210314_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='serversetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.TextField(blank=True, null=True)),
                ('server_username', models.TextField(blank=True, null=True)),
                ('server_password', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
