# Generated by Django 3.0.7 on 2021-02-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0014_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='money',
        ),
    ]
