# Generated by Django 3.0.7 on 2021-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0015_delete_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_scan_results_db',
            name='consequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual_scan_results_db',
            name='likelihood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual_scan_results_db',
            name='risk_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
