# Generated by Django 3.0.7 on 2021-04-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0017_auto_20210410_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_scan_results_db',
            old_name='scan_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='manual_scans_db',
            old_name='scan_id',
            new_name='client_id',
        ),
    ]
