# Generated by Django 3.0.7 on 2021-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0018_auto_20210411_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_scan_results_db',
            name='scan_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual_scans_db',
            name='scan_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
