# Generated by Django 3.0.7 on 2021-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0019_auto_20210411_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_scan_results_db',
            name='vuln_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
