# Generated by Django 3.0.7 on 2021-04-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_scan', '0020_auto_20210413_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_scans_db',
            name='critical_vul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual_scans_db',
            name='very_low_vul',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
