# Generated by Django 3.0.7 on 2021-03-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200503_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmap_scan_db',
            name='date_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
