# Generated by Django 3.0.7 on 2021-03-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_dirsearch_result_db_dirsearch_scan_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirsearch_result_db',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dirsearch_scan_db',
            name='total_dirs',
            field=models.IntegerField(default=0),
        ),
    ]
