# Generated by Django 3.0.7 on 2021-03-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_openvas_scan_db_ov_scan_result_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ov_scan_result_db',
            new_name='openvas_result_db',
        ),
    ]
