# Generated by Django 3.0.7 on 2021-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20210309_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvas_result_db',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openvas_scan_db',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
