# Generated by Django 3.0.7 on 2021-04-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_sniper_config_db_sniper_result_db_sniper_scan_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sniper_config_db',
            old_name='result',
            new_name='result2',
        ),
    ]
