# Generated by Django 3.0.7 on 2021-04-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20210420_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniper_config_db',
            name='project_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
