# Generated by Django 3.0.7 on 2021-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_sniper_config_db_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sniper_result_db',
            old_name='redirection',
            new_name='config_id',
        ),
        migrations.RenameField(
            model_name='sniper_result_db',
            old_name='scan_id',
            new_name='dns',
        ),
        migrations.RenameField(
            model_name='sniper_result_db',
            old_name='size',
            new_name='vuln_id',
        ),
        migrations.RenameField(
            model_name='sniper_scan_db',
            old_name='total_dirs',
            new_name='total_sniper',
        ),
        migrations.RemoveField(
            model_name='sniper_result_db',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sniper_result_db',
            name='url',
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='config_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
