# Generated by Django 3.0.7 on 2021-04-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20210422_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniper_result_db',
            name='scan_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='config_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
