# Generated by Django 3.0.7 on 2021-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20210423_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sniper_result_db',
            old_name='dns',
            new_name='output',
        ),
        migrations.AddField(
            model_name='sniper_result_db',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
