# Generated by Django 3.0.7 on 2021-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20210424_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniper_result_db',
            name='result_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='log_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
