# Generated by Django 3.0.7 on 2021-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20210427_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sniper_result_db',
            name='result_file',
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='result_file1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='result_file2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
