# Generated by Django 3.0.7 on 2021-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20210427_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniper_scan_db',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='result1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniper_scan_db',
            name='result2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
