# Generated by Django 3.0.7 on 2021-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_auto_20210427_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniper_config_db',
            name='last_scan_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
