# Generated by Django 3.0.7 on 2021-06-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_sniper_config_db_last_scan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='audit_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(blank=True, null=True)),
                ('question_id', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='audit_question_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_group', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
