# Generated by Django 3.0.7 on 2021-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_audit_db_answer_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='audit_question_group_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_group_id', models.TextField(blank=True, null=True)),
                ('question_group', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='audit_question_db',
            old_name='question_group',
            new_name='question_group_id',
        ),
        migrations.AddField(
            model_name='audit_question_db',
            name='question_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
