# Generated by Django 3.0.7 on 2021-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_auto_20210622_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_db',
            name='question_group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
