# Generated by Django 3.0.7 on 2021-06-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_auto_20210624_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audit_answer_db',
        ),
        migrations.RenameField(
            model_name='audit_db',
            old_name='answer_id',
            new_name='answer',
        ),
    ]
