# Generated by Django 3.0.7 on 2021-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20210624_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_db',
            name='accept',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_db',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_db',
            name='client_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
