# Generated by Django 3.0.7 on 2021-07-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0028_auto_20210706_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_db',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_db',
            name='flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit_db',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_question_db',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='audit_question_group_db',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
